package autoscaler

import mock "github.com/stretchr/testify/mock"

// MockMetricProvider is an autogenerated mock type for the MetricProvider type
type MockMetricProvider struct {
	mock.Mock
}

// Values provides a mock function with given fields: instances
func (_m *MockMetricProvider) Values(instances Instances) (Metric, error) {
	ret := _m.Called(instances)

	var r0 Metric
	if rf, ok := ret.Get(0).(func(Instances) Metric); ok {
		r0 = rf(instances)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Metric)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Instances) error); ok {
		r1 = rf(instances)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ MetricProvider = (*MockMetricProvider)(nil)
